### ISSUE TITLE
Robustness value incorrect

### ISSUE THREAD

**Issue by ChaitraKeshavaMurthy** [decyphir/STLRom#1]
When we add data that violate the rule in between the samples, the robustness value returned is always positive. 
Consider the Example where sample data is {-1,-1,-1,-1,-1,1,1,1,1}
Suppose if we are checking a rule x[t] < 0 , the robustness returned is positive . Shouldn't it be negative value indicating the violation of rule?

**Comment by adonze** [comment]
The rule x[t]<0 is interpreted as x[t==0] < 0. Assuming your time vector is {0, 1, 2, 3, ..., 8}, only the first sample is used, i.e., -1. Since it is negative, the rule is satisfied, so the robustness is positive (equal to 1) as there is no violation. 

If you use a temporal operator, e.g.,  alw_[0, 9] (x[t] < 0), then all samples are evaluated and the robustness shall be negative, because of x[t==6]>0.

**Comment by ChaitraKeshavaMurthy** [comment]
Thank you for your reply. Below the rule to be satisfied 
signal x
phi := alw_[0,11] (x[t] < 0.5)

This is my sample data
v = {0,0,0,0,0,0,1,1,1,0,0,0};

In this case I expect my robustness to be in negative since the I have data violating the rule i.e 1 in the position 6,7,8.
But I get the robustness value as 0.5
